/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gibbonsdimarco_yamec_app_jni_SystemMonitorManagerJNI */

#ifndef _Included_com_gibbonsdimarco_yamec_app_jni_SystemMonitorManagerJNI
#define _Included_com_gibbonsdimarco_yamec_app_jni_SystemMonitorManagerJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gibbonsdimarco_yamec_app_jni_SystemMonitorManagerJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gibbonsdimarco_yamec_app_jni_SystemMonitorManagerJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
